version: '3.4'

services:
  eveningviewingserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EveningViewingDB;User Id=sa;Password=S3cur3P@ssW0rd!
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_USER: "myuser"
      MSSQL_PASSWORD: "mypassword"
